import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#fdf9f1',
        'on-background': '#1c1c17',
        surface: '#fdf9f1',
        'on-surface': '#1c1c17',
        'surface-dim': '#dddad2',
        'surface-bright': '#fdf9f1',
        'surface-variant': '#e6e2da',
        'on-surface-variant': '#434844',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3eb',
        'surface-container': '#f1ede6',
        'surface-container-high': '#ece8e0',
        'surface-container-highest': '#e6e2da',
        'surface-tint': '#55615a',
        primary: '#1f2a24',
        'on-primary': '#ffffff',
        'primary-container': '#1f2a24',
        'on-primary-container': '#859289',
        'inverse-primary': '#bdcac1',
        'primary-fixed': '#d9e6dc',
        'primary-fixed-dim': '#bdcac1',
        'on-primary-fixed': '#131e18',
        'on-primary-fixed-variant': '#3e4943',
        secondary: '#556251',
        'on-secondary': '#ffffff',
        'secondary-container': '#d8e7d1',
        'on-secondary-container': '#5b6857',
        'secondary-fixed': '#d8e7d1',
        'secondary-fixed-dim': '#bccbb6',
        'on-secondary-fixed': '#131e11',
        'on-secondary-fixed-variant': '#3d4a3a',
        tertiary: '#c86d51',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#4f1200',
        'on-tertiary-container': '#d37559',
        'tertiary-fixed': '#ffdbd0',
        'tertiary-fixed-dim': '#ffb59f',
        'on-tertiary-fixed': '#3a0a00',
        'on-tertiary-fixed-variant': '#793019',
        outline: '#737874',
        'outline-variant': '#ddd6c8',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'inverse-surface': '#31302b',
        'inverse-on-surface': '#f4f0e8',
        ivory: '#FDFBF7',
        sand: '#F5EFE6',
        'sand-light': '#F9F6F0',
        forest: '#1F2A24',
        sage: '#7D8B78',
        terracotta: '#C86D51',
        charcoal: '#1C1C17',
      },
      fontFamily: {
        serif: ['var(--font-newsreader)', 'Newsreader', 'serif'],
        sans: ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['var(--font-newsreader)', 'serif'],
        'headline-lg': ['var(--font-newsreader)', 'serif'],
        'headline-md': ['var(--font-newsreader)', 'serif'],
        'headline-sm': ['var(--font-newsreader)', 'serif'],
        'quote-lg': ['var(--font-newsreader)', 'serif'],
        'body-lg': ['var(--font-plus-jakarta)', 'sans-serif'],
        'body-md': ['var(--font-plus-jakarta)', 'sans-serif'],
        'body-sm': ['var(--font-plus-jakarta)', 'sans-serif'],
        'label-md': ['var(--font-plus-jakarta)', 'sans-serif'],
        'label-sm': ['var(--font-plus-jakarta)', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em' }],
        'display-lg-mobile': ['38px', { lineHeight: '44px', letterSpacing: '-0.01em' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.015em' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px' }],
        'headline-md': ['28px', { lineHeight: '36px' }],
        'headline-sm': ['22px', { lineHeight: '30px' }],
        'quote-lg': ['24px', { lineHeight: '38px' }],
        'body-lg': ['18px', { lineHeight: '30px', letterSpacing: '-0.005em' }],
        'body-md': ['16px', { lineHeight: '26px' }],
        'body-sm': ['14px', { lineHeight: '22px' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.12em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.14em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '2rem',
        'gutter-mobile': '1rem',
        margin: '4rem',
        'margin-mobile': '1.5rem',
        'space-xs': '0.375rem',
        'space-sm': '0.75rem',
        'space-md': '1.25rem',
        'space-lg': '2.25rem',
        'space-xl': '4rem',
      },
    },
  },
  plugins: [],
};

export default config;
